### PR TITLE
Issue #16. Implemented _requestPromised method.

### PR DESCRIPTION
**Pull request by wallybh**
Hi.

I implemented a Promise version to your library. I saw the issue #16 and thought it would be a good idea to help with that.

I implemented the function _requestPromised. It'll do the same thing in _request function, but returning a Promise instead.

To prevent breaking change, I'll call that function only if the caller do not pass the callback parameter.

I wrote some unit tests also.

Please feel free to criticize my code.

PS: I apologize for any english mistakes from my part.

### CODE REVIEW

**Comment by dutu** [comment]
@wallybh, this is excellent!!
do you think it would it be possible to extend the unit test into integration test, i.e. in addition to verify that the result of the promise is an object/array/error (similar as for the callback case?)

**Comment by wallybh** [comment]
Sure. I'm writing right now.

**Comment by wallybh** [comment]
@dutu I copied your 'should return data' tests and adapted to use promise. Also, I reorganized the other integration tests I created on previously commit. Please, check it out.

**Comment by dutu** [comment]
@wallybh, thank you for this excellent PR and your great contribution!

**Pull request merged**
