### PR TITLE
Adding the ability to pass in a nonce generating function.

### PR DESCRIPTION
**Pull request by SeanRobb**
This will use a nonce generating function when one is passed in via the options object.

### CODE REVIEW

**Comment by dutu** [comment]
@SeanRobb what would be the use case of this feature? When do you think the built in nonce generator can't be used?

**Comment by SeanRobb** [comment]
@dutu I am building a service that is comprised of multiple microservices using multiple languages, because of the this pattern I need to have all of my services using the same nonce generating algorithm. I figured since I needed this some others might as well.  Another use case is to guarantee that nonces are incrementing in parallel streams.  This could allow someone to create a function the guarantees this incrementing nonce if needed.

**Comment by joemccann** [comment]
Yes huge +1 on this.  I keep running into this issue:

```bash
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Poloniex error 422: . Nonce must be greater than 151450037271500. You provided 151450037204200.
```

**Comment by joemccann** [comment]
Also, I patched the lib to simply pass in a larger integer to the `nonce` function

```js
    param.nonce = this.options && this.options.nonce ? nonce(this.options.nonce) : nonce(16);
```

Then...

```js
let poloniex = new Poloniex(POLO_CREDS.key, POLO_CREDS.secret,
  { socketTimeout: 10000, nonce: 32})
```

I've had way fewer race condition issues from Poloniex since I changed to 32.

**Comment by dutu** [comment]
@SeanRobb, I will merge your PR; your contribution is appreciated.
However, I am afraid the functionality will not serve your purpose.
From past observations, there is very high probability that, for API calls sent at short interval one after each other, Poloniex server still returns nonce error even if the nonce is ever increasing.
I'm not sure if the issue is only due to the possibility of consecutive API calls to arrive at the destination server in reversed order, or also by inappropriate handling by Polonie; but this is my observation from (relatively) long time usage of Poloniex API interface.

**Comment by SeanRobb** [comment]
For me just being able to write my own nonce generation function would be amazing.
Thank you for the merge!

**Pull request merged**
